export type Opcode = {
  name: string;
  description: string;
  hex: number;
  bytesCount: number;
  addOneIfMemory16Bits?: boolean;
  addOneIfIndex16Bits?: boolean;
};

const OPCODES: Opcode[] = [
  {
    name: 'ADC (dp,X)',
    description: 'Add With Carry',
    hex: 0x61,
    bytesCount: 2,
  },
  { name: 'ADC sr,S', description: 'Add With Carry', hex: 0x63, bytesCount: 2 },
  { name: 'ADC dp', description: 'Add With Carry', hex: 0x65, bytesCount: 2 },
  { name: 'ADC [dp]', description: 'Add With Carry', hex: 0x67, bytesCount: 2 },
  {
    name: 'ADC #const',
    description: 'Add With Carry',
    hex: 0x69,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  { name: 'ADC addr', description: 'Add With Carry', hex: 0x6d, bytesCount: 3 },
  { name: 'ADC long', description: 'Add With Carry', hex: 0x6f, bytesCount: 4 },
  {
    name: 'ADC ( dp),Y',
    description: 'Add With Carry',
    hex: 0x71,
    bytesCount: 2,
  },
  { name: 'ADC (dp)', description: 'Add With Carry', hex: 0x72, bytesCount: 2 },
  {
    name: 'ADC (sr,S),Y',
    description: 'Add With Carry',
    hex: 0x73,
    bytesCount: 2,
  },
  { name: 'ADC dp,X', description: 'Add With Carry', hex: 0x75, bytesCount: 2 },
  {
    name: 'ADC [dp],Y',
    description: 'Add With Carry',
    hex: 0x77,
    bytesCount: 2,
  },
  {
    name: 'ADC addr,Y',
    description: 'Add With Carry',
    hex: 0x79,
    bytesCount: 3,
  },
  {
    name: 'ADC addr,X',
    description: 'Add With Carry',
    hex: 0x7d,
    bytesCount: 3,
  },
  {
    name: 'ADC long,X',
    description: 'Add With Carry',
    hex: 0x7f,
    bytesCount: 4,
  },
  {
    name: 'AND (dp,X)',
    description: 'AND Accumulator with Memory',
    hex: 0x21,
    bytesCount: 2,
  },
  {
    name: 'AND sr,S',
    description: 'AND Accumulator with Memory',
    hex: 0x23,
    bytesCount: 2,
  },
  {
    name: 'AND dp',
    description: 'AND Accumulator with Memory',
    hex: 0x25,
    bytesCount: 2,
  },
  {
    name: 'AND [dp]',
    description: 'AND Accumulator with Memory',
    hex: 0x27,
    bytesCount: 2,
  },
  {
    name: 'AND #const',
    description: 'AND Accumulator with Memory',
    hex: 0x29,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'AND addr',
    description: 'AND Accumulator with Memory',
    hex: 0x2d,
    bytesCount: 3,
  },
  {
    name: 'AND long',
    description: 'AND Accumulator with Memory',
    hex: 0x2f,
    bytesCount: 4,
  },
  {
    name: 'AND (dp),Y',
    description: 'AND Accumulator with Memory',
    hex: 0x31,
    bytesCount: 2,
  },
  {
    name: 'AND (dp)',
    description: 'AND Accumulator with Memory',
    hex: 0x32,
    bytesCount: 2,
  },
  {
    name: 'AND (sr,S),Y',
    description: 'AND Accumulator with Memory',
    hex: 0x33,
    bytesCount: 2,
  },
  {
    name: 'AND dp,X',
    description: 'AND Accumulator with Memory',
    hex: 0x35,
    bytesCount: 2,
  },
  {
    name: 'AND [dp],Y',
    description: 'AND Accumulator with Memory',
    hex: 0x37,
    bytesCount: 2,
  },
  {
    name: 'AND addr,Y',
    description: 'AND Accumulator with Memory',
    hex: 0x39,
    bytesCount: 3,
  },
  {
    name: 'AND addr,X',
    description: 'AND Accumulator with Memory',
    hex: 0x3d,
    bytesCount: 3,
  },
  {
    name: 'AND long,X',
    description: 'AND Accumulator with Memory',
    hex: 0x3f,
    bytesCount: 4,
  },
  {
    name: 'ASL dp',
    description: 'Arithmetic Shift Left',
    hex: 0x6,
    bytesCount: 2,
  },
  {
    name: 'ASL A',
    description: 'Arithmetic Shift Left',
    hex: 0x0a,
    bytesCount: 1,
  },
  {
    name: 'ASL addr',
    description: 'Arithmetic Shift Left',
    hex: 0x0e,
    bytesCount: 3,
  },
  {
    name: 'ASL dp,X',
    description: 'Arithmetic Shift Left',
    hex: 0x16,
    bytesCount: 2,
  },
  {
    name: 'ASL addr,X',
    description: 'Arithmetic Shift Left',
    hex: 0x1e,
    bytesCount: 3,
  },
  {
    name: 'BCC nearlabel (BLT)',
    description: 'Branch if Carry Clear',
    hex: 0x90,
    bytesCount: 2,
  },
  {
    name: 'BCS nearlabel (BGE)',
    description: 'Branch if Carry Set',
    hex: 0xb0,
    bytesCount: 2,
  },
  {
    name: 'BEQ nearlabel',
    description: 'Branch if Equal',
    hex: 0xf0,
    bytesCount: 2,
  },
  { name: 'BIT dp', description: 'Test Bits', hex: 0x24, bytesCount: 2 },
  { name: 'BIT addr', description: 'Test Bits', hex: 0x2c, bytesCount: 3 },
  { name: 'BIT dp,X', description: 'Test Bits', hex: 0x34, bytesCount: 2 },
  { name: 'BIT addr,X', description: 'Test Bits', hex: 0x3c, bytesCount: 3 },
  {
    name: 'BIT #const',
    description: 'Test Bits',
    hex: 0x89,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'BMI nearlabel',
    description: 'Branch if Minus',
    hex: 0x30,
    bytesCount: 2,
  },
  {
    name: 'BNE nearlabel',
    description: 'Branch if Not Equal',
    hex: 0xd0,
    bytesCount: 2,
  },
  {
    name: 'BPL nearlabel',
    description: 'Branch if Plus',
    hex: 0x10,
    bytesCount: 2,
  },
  {
    name: 'BRA nearlabel',
    description: 'Branch Always',
    hex: 0x80,
    bytesCount: 2,
  },
  { name: 'BRK', description: 'Break', hex: 0x0, bytesCount: 2 },
  {
    name: 'BRL label',
    description: 'Branch Long Always',
    hex: 0x82,
    bytesCount: 3,
  },
  {
    name: 'BVC nearlabel',
    description: 'Branch if Overflow Clear',
    hex: 0x50,
    bytesCount: 2,
  },
  {
    name: 'BVS nearlabel',
    description: 'Branch if Overflow Set',
    hex: 0x70,
    bytesCount: 2,
  },
  { name: 'CLC', description: 'Clear Carry', hex: 0x18, bytesCount: 1 },
  {
    name: 'CLD',
    description: 'Clear Decimal Mode Flag',
    hex: 0xd8,
    bytesCount: 1,
  },
  {
    name: 'CLI',
    description: 'Clear Interrupt Disable Flag',
    hex: 0x58,
    bytesCount: 1,
  },
  { name: 'CLV', description: 'Clear Overflow Flag', hex: 0xb8, bytesCount: 1 },
  {
    name: 'CMP (dp,X)',
    description: 'Compare Accumulator with Memory',
    hex: 0xc1,
    bytesCount: 2,
  },
  {
    name: 'CMP sr,S',
    description: 'Compare Accumulator with Memory',
    hex: 0xc3,
    bytesCount: 2,
  },
  {
    name: 'CMP dp',
    description: 'Compare Accumulator with Memory',
    hex: 0xc5,
    bytesCount: 2,
  },
  {
    name: 'CMP [dp]',
    description: 'Compare Accumulator with Memory',
    hex: 0xc7,
    bytesCount: 2,
  },
  {
    name: 'CMP #const',
    description: 'Compare Accumulator with Memory',
    hex: 0xc9,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'CMP addr',
    description: 'Compare Accumulator with Memory',
    hex: 0xcd,
    bytesCount: 3,
  },
  {
    name: 'CMP long',
    description: 'Compare Accumulator with Memory',
    hex: 0xcf,
    bytesCount: 4,
  },
  {
    name: 'CMP (dp),Y',
    description: 'Compare Accumulator with Memory',
    hex: 0xd1,
    bytesCount: 2,
  },
  {
    name: 'CMP (dp)',
    description: 'Compare Accumulator with Memory',
    hex: 0xd2,
    bytesCount: 2,
  },
  {
    name: 'CMP (sr,S),Y',
    description: 'Compare Accumulator with Memory',
    hex: 0xd3,
    bytesCount: 2,
  },
  {
    name: 'CMP dp,X',
    description: 'Compare Accumulator with Memory',
    hex: 0xd5,
    bytesCount: 2,
  },
  {
    name: 'CMP [dp],Y',
    description: 'Compare Accumulator with Memory',
    hex: 0xd7,
    bytesCount: 2,
  },
  {
    name: 'CMP addr,Y',
    description: 'Compare Accumulator with Memory',
    hex: 0xd9,
    bytesCount: 3,
  },
  {
    name: 'CMP addr,X',
    description: 'Compare Accumulator with Memory',
    hex: 0xdd,
    bytesCount: 3,
  },
  {
    name: 'CMP long,X',
    description: 'Compare Accumulator with Memory',
    hex: 0xdf,
    bytesCount: 4,
  },
  { name: 'COP #const', description: 'Co-Processor', hex: 0x2, bytesCount: 2 },
  {
    name: 'CPX #const',
    description: 'Compare Index Register X with Memory',
    hex: 0xe0,
    bytesCount: 2,
    addOneIfIndex16Bits: true,
  },
  {
    name: 'CPX dp',
    description: 'Compare Index Register X with Memory',
    hex: 0xe4,
    bytesCount: 2,
  },
  {
    name: 'CPX addr',
    description: 'Compare Index Register X with Memory',
    hex: 0xec,
    bytesCount: 3,
  },
  {
    name: 'CPY #const',
    description: 'Compare Index Register Y with Memory',
    hex: 0xc0,
    bytesCount: 2,
    addOneIfIndex16Bits: true,
  },
  {
    name: 'CPY dp',
    description: 'Compare Index Register Y with Memory',
    hex: 0xc4,
    bytesCount: 2,
  },
  {
    name: 'CPY addr',
    description: 'Compare Index Register Y with Memory',
    hex: 0xcc,
    bytesCount: 3,
  },
  { name: 'DEC A (DEA)', description: 'Decrement', hex: 0x3a, bytesCount: 1 },
  { name: 'DEC dp', description: 'Decrement', hex: 0xc6, bytesCount: 2 },
  { name: 'DEC addr', description: 'Decrement', hex: 0xce, bytesCount: 3 },
  { name: 'DEC dp,X', description: 'Decrement', hex: 0xd6, bytesCount: 2 },
  { name: 'DEC addr,X', description: 'Decrement', hex: 0xde, bytesCount: 3 },
  {
    name: 'DEX',
    description: 'Decrement Index Register X',
    hex: 0xca,
    bytesCount: 1,
  },
  {
    name: 'DEY',
    description: 'Decrement Index Register Y',
    hex: 0x88,
    bytesCount: 1,
  },
  {
    name: 'EOR (dp,X)',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x41,
    bytesCount: 2,
  },
  {
    name: 'EOR sr,S',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x43,
    bytesCount: 2,
  },
  {
    name: 'EOR dp',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x45,
    bytesCount: 2,
  },
  {
    name: 'EOR [dp]',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x47,
    bytesCount: 2,
  },
  {
    name: 'EOR #const',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x49,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'EOR addr',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x4d,
    bytesCount: 3,
  },
  {
    name: 'EOR long',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x4f,
    bytesCount: 4,
  },
  {
    name: 'EOR (dp),Y',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x51,
    bytesCount: 2,
  },
  {
    name: 'EOR (dp)',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x52,
    bytesCount: 2,
  },
  {
    name: 'EOR (sr,S),Y',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x53,
    bytesCount: 2,
  },
  {
    name: 'EOR dp,X',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x55,
    bytesCount: 2,
  },
  {
    name: 'EOR [dp],Y',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x57,
    bytesCount: 2,
  },
  {
    name: 'EOR addr,Y',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x59,
    bytesCount: 3,
  },
  {
    name: 'EOR addr,X',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x5d,
    bytesCount: 3,
  },
  {
    name: 'EOR long,X',
    description: 'Exclusive-OR Accumulator with Memory',
    hex: 0x5f,
    bytesCount: 4,
  },
  { name: 'INC A (INA)', description: 'Increment', hex: 0x1a, bytesCount: 1 },
  { name: 'INC dp', description: 'Increment', hex: 0xe6, bytesCount: 2 },
  { name: 'INC addr', description: 'Increment', hex: 0xee, bytesCount: 3 },
  { name: 'INC dp,X', description: 'Increment', hex: 0xf6, bytesCount: 2 },
  { name: 'INC addr,X', description: 'Increment', hex: 0xfe, bytesCount: 3 },
  {
    name: 'INX',
    description: 'Increment Index Register X',
    hex: 0xe8,
    bytesCount: 1,
  },
  {
    name: 'INY',
    description: 'Increment Index Register Y',
    hex: 0xc8,
    bytesCount: 1,
  },
  { name: 'JMP addr', description: 'Jump', hex: 0x4c, bytesCount: 3 },
  { name: 'JMP long (JML)', description: 'Jump', hex: 0x5c, bytesCount: 4 },
  { name: 'JMP (addr)', description: 'Jump', hex: 0x6c, bytesCount: 3 },
  { name: 'JMP (addr,X)', description: 'Jump', hex: 0x7c, bytesCount: 3 },
  { name: 'JMP [addr] (JML)', description: 'Jump', hex: 0xdc, bytesCount: 3 },
  {
    name: 'JSR addr',
    description: 'Jump to Subroutine',
    hex: 0x20,
    bytesCount: 3,
  },
  {
    name: 'JSR long (JSL)',
    description: 'Jump to Subroutine',
    hex: 0x22,
    bytesCount: 4,
  },
  {
    name: 'JSR (addr,X))',
    description: 'Jump to Subroutine',
    hex: 0xfc,
    bytesCount: 3,
  },
  {
    name: 'LDA (dp,X)',
    description: 'Load Accumulator from Memory',
    hex: 0xa1,
    bytesCount: 2,
  },
  {
    name: 'LDA sr,S',
    description: 'Load Accumulator from Memory',
    hex: 0xa3,
    bytesCount: 2,
  },
  {
    name: 'LDA dp',
    description: 'Load Accumulator from Memory',
    hex: 0xa5,
    bytesCount: 2,
  },
  {
    name: 'LDA [dp]',
    description: 'Load Accumulator from Memory',
    hex: 0xa7,
    bytesCount: 2,
  },
  {
    name: 'LDA #const',
    description: 'Load Accumulator from Memory',
    hex: 0xa9,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'LDA addr',
    description: 'Load Accumulator from Memory',
    hex: 0xad,
    bytesCount: 3,
  },
  {
    name: 'LDA long',
    description: 'Load Accumulator from Memory',
    hex: 0xaf,
    bytesCount: 4,
  },
  {
    name: 'LDA (dp),Y',
    description: 'Load Accumulator from Memory',
    hex: 0xb1,
    bytesCount: 2,
  },
  {
    name: 'LDA (dp)',
    description: 'Load Accumulator from Memory',
    hex: 0xb2,
    bytesCount: 2,
  },
  {
    name: 'LDA (sr,S),Y',
    description: 'Load Accumulator from Memory',
    hex: 0xb3,
    bytesCount: 2,
  },
  {
    name: 'LDA dp,X',
    description: 'Load Accumulator from Memory',
    hex: 0xb5,
    bytesCount: 2,
  },
  {
    name: 'LDA [dp],Y',
    description: 'Load Accumulator from Memory',
    hex: 0xb7,
    bytesCount: 2,
  },
  {
    name: 'LDA addr,Y',
    description: 'Load Accumulator from Memory',
    hex: 0xb9,
    bytesCount: 3,
  },
  {
    name: 'LDA addr,X',
    description: 'Load Accumulator from Memory',
    hex: 0xbd,
    bytesCount: 3,
  },
  {
    name: 'LDA long,X',
    description: 'Load Accumulator from Memory',
    hex: 0xbf,
    bytesCount: 4,
  },
  {
    name: 'LDX #const',
    description: 'Load Index Register X from Memory',
    hex: 0xa2,
    bytesCount: 2,
    addOneIfIndex16Bits: true,
  },
  {
    name: 'LDX dp',
    description: 'Load Index Register X from Memory',
    hex: 0xa6,
    bytesCount: 2,
  },
  {
    name: 'LDX addr',
    description: 'Load Index Register X from Memory',
    hex: 0xae,
    bytesCount: 3,
  },
  {
    name: 'LDX dp,Y',
    description: 'Load Index Register X from Memory',
    hex: 0xb6,
    bytesCount: 2,
  },
  {
    name: 'LDX addr,Y',
    description: 'Load Index Register X from Memory',
    hex: 0xbe,
    bytesCount: 3,
  },
  {
    name: 'LDY #const',
    description: 'Load Index Register Y from Memory',
    hex: 0xa0,
    bytesCount: 2,
    addOneIfIndex16Bits: true,
  },
  {
    name: 'LDY dp',
    description: 'Load Index Register Y from Memory',
    hex: 0xa4,
    bytesCount: 2,
  },
  {
    name: 'LDY addr',
    description: 'Load Index Register Y from Memory',
    hex: 0xac,
    bytesCount: 3,
  },
  {
    name: 'LDY dp,X',
    description: 'Load Index Register Y from Memory',
    hex: 0xb4,
    bytesCount: 2,
  },
  {
    name: 'LDY addr,X',
    description: 'Load Index Register Y from Memory',
    hex: 0xbc,
    bytesCount: 3,
  },
  {
    name: 'LSR dp',
    description: 'Logical Shift Memory or Accumulator Right',
    hex: 0x46,
    bytesCount: 2,
  },
  {
    name: 'LSR A',
    description: 'Logical Shift Memory or Accumulator Right',
    hex: 0x4a,
    bytesCount: 1,
  },
  {
    name: 'LSR addr',
    description: 'Logical Shift Memory or Accumulator Right',
    hex: 0x4e,
    bytesCount: 3,
  },
  {
    name: 'LSR dp,X',
    description: 'Logical Shift Memory or Accumulator Right',
    hex: 0x56,
    bytesCount: 2,
  },
  {
    name: 'LSR addr,X',
    description: 'Logical Shift Memory or Accumulator Right',
    hex: 0x5e,
    bytesCount: 3,
  },
  {
    name: 'MVN srcbk,destbk',
    description: 'Block Move Negative',
    hex: 0x54,
    bytesCount: 3,
  },
  {
    name: 'MVP srcbk,destbk',
    description: 'Block Move Positive',
    hex: 0x44,
    bytesCount: 3,
  },
  { name: 'NOP', description: 'No Operation', hex: 0xea, bytesCount: 1 },
  {
    name: 'ORA (dp,X)',
    description: 'OR Accumulator with Memory',
    hex: 0x1,
    bytesCount: 2,
  },
  {
    name: 'ORA sr,S',
    description: 'OR Accumulator with Memory',
    hex: 0x3,
    bytesCount: 2,
  },
  {
    name: 'ORA dp',
    description: 'OR Accumulator with Memory',
    hex: 0x5,
    bytesCount: 2,
  },
  {
    name: 'ORA [dp]',
    description: 'OR Accumulator with Memory',
    hex: 0x7,
    bytesCount: 2,
  },
  {
    name: 'ORA #const',
    description: 'OR Accumulator with Memory',
    hex: 0x9,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'ORA addr',
    description: 'OR Accumulator with Memory',
    hex: 0x0d,
    bytesCount: 3,
  },
  {
    name: 'ORA long',
    description: 'OR Accumulator with Memory',
    hex: 0x0f,
    bytesCount: 4,
  },
  {
    name: 'ORA (dp),Y',
    description: 'OR Accumulator with Memory',
    hex: 0x11,
    bytesCount: 2,
  },
  {
    name: 'ORA (dp)',
    description: 'OR Accumulator with Memory',
    hex: 0x12,
    bytesCount: 2,
  },
  {
    name: 'ORA (sr,S),Y',
    description: 'OR Accumulator with Memory',
    hex: 0x13,
    bytesCount: 2,
  },
  {
    name: 'ORA dp,X',
    description: 'OR Accumulator with Memory',
    hex: 0x15,
    bytesCount: 2,
  },
  {
    name: 'ORA [dp],Y',
    description: 'OR Accumulator with Memory',
    hex: 0x17,
    bytesCount: 2,
  },
  {
    name: 'ORA addr,Y',
    description: 'OR Accumulator with Memory',
    hex: 0x19,
    bytesCount: 3,
  },
  {
    name: 'ORA addr,X',
    description: 'OR Accumulator with Memory',
    hex: 0x1d,
    bytesCount: 3,
  },
  {
    name: 'ORA long,X',
    description: 'OR Accumulator with Memory',
    hex: 0x1f,
    bytesCount: 4,
  },
  {
    name: 'PEA addr',
    description: 'Push Effective Absolute Address',
    hex: 0xf4,
    bytesCount: 3,
  },
  {
    name: 'PEI (dp)',
    description: 'Push Effective Indirect Address',
    hex: 0xd4,
    bytesCount: 2,
  },
  {
    name: 'PER label',
    description: 'Push Effective PC Relative Indirect Address',
    hex: 0x62,
    bytesCount: 3,
  },
  { name: 'PHA', description: 'Push Accumulator', hex: 0x48, bytesCount: 1 },
  {
    name: 'PHB',
    description: 'Push Data Bank Register',
    hex: 0x8b,
    bytesCount: 1,
  },
  {
    name: 'PHD',
    description: 'Push Direct Page Register',
    hex: 0x0b,
    bytesCount: 1,
  },
  {
    name: 'PHK',
    description: 'Push Program Bank Register',
    hex: 0x4b,
    bytesCount: 1,
  },
  {
    name: 'PHP',
    description: 'Push Processor Status Register',
    hex: 0x8,
    bytesCount: 1,
  },
  {
    name: 'PHX',
    description: 'Push Index Register X',
    hex: 0xda,
    bytesCount: 1,
  },
  {
    name: 'PHY',
    description: 'Push Index Register Y',
    hex: 0x5a,
    bytesCount: 1,
  },
  { name: 'PLA', description: 'Pull Accumulator', hex: 0x68, bytesCount: 1 },
  {
    name: 'PLB',
    description: 'Pull Data Bank Register',
    hex: 0xab,
    bytesCount: 1,
  },
  {
    name: 'PLD',
    description: 'Pull Direct Page Register',
    hex: 0x2b,
    bytesCount: 1,
  },
  {
    name: 'PLP',
    description: 'Pull Processor Status Register',
    hex: 0x28,
    bytesCount: 1,
  },
  {
    name: 'PLX',
    description: 'Pull Index Register X',
    hex: 0xfa,
    bytesCount: 1,
  },
  {
    name: 'PLY',
    description: 'Pull Index Register Y',
    hex: 0x7a,
    bytesCount: 1,
  },
  {
    name: 'REP #const',
    description: 'Reset Processor Status Bits',
    hex: 0xc2,
    bytesCount: 2,
  },
  {
    name: 'ROL dp',
    description: 'Rotate Memory or Accumulator Left',
    hex: 0x26,
    bytesCount: 2,
  },
  {
    name: 'ROL A',
    description: 'Rotate Memory or Accumulator Left',
    hex: 0x2a,
    bytesCount: 1,
  },
  {
    name: 'ROL addr',
    description: 'Rotate Memory or Accumulator Left',
    hex: 0x2e,
    bytesCount: 3,
  },
  {
    name: 'ROL dp,X',
    description: 'Rotate Memory or Accumulator Left',
    hex: 0x36,
    bytesCount: 2,
  },
  {
    name: 'ROL addr,X',
    description: 'Rotate Memory or Accumulator Left',
    hex: 0x3e,
    bytesCount: 3,
  },
  {
    name: 'ROR dp',
    description: 'Rotate Memory or Accumulator Right',
    hex: 0x66,
    bytesCount: 2,
  },
  {
    name: 'ROR A',
    description: 'Rotate Memory or Accumulator Right',
    hex: 0x6a,
    bytesCount: 1,
  },
  {
    name: 'ROR addr',
    description: 'Rotate Memory or Accumulator Right',
    hex: 0x6e,
    bytesCount: 3,
  },
  {
    name: 'ROR dp,X',
    description: 'Rotate Memory or Accumulator Right',
    hex: 0x76,
    bytesCount: 2,
  },
  {
    name: 'ROR addr,X',
    description: 'Rotate Memory or Accumulator Right',
    hex: 0x7e,
    bytesCount: 3,
  },
  {
    name: 'RTI',
    description: 'Return from Interrupt',
    hex: 0x40,
    bytesCount: 1,
  },
  {
    name: 'RTL',
    description: 'Return from Subroutine Long',
    hex: 0x6b,
    bytesCount: 1,
  },
  {
    name: 'RTS',
    description: 'Return from Subroutine',
    hex: 0x60,
    bytesCount: 1,
  },
  {
    name: 'SBC (dp,X)',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xe1,
    bytesCount: 2,
  },
  {
    name: 'SBC sr,S',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xe3,
    bytesCount: 2,
  },
  {
    name: 'SBC dp',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xe5,
    bytesCount: 2,
  },
  {
    name: 'SBC [dp]',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xe7,
    bytesCount: 2,
  },
  {
    name: 'SBC #const',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xe9,
    bytesCount: 2,
    addOneIfMemory16Bits: true,
  },
  {
    name: 'SBC addr',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xed,
    bytesCount: 3,
  },
  {
    name: 'SBC long',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xef,
    bytesCount: 4,
  },
  {
    name: 'SBC (dp),Y',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xf1,
    bytesCount: 2,
  },
  {
    name: 'SBC (dp)',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xf2,
    bytesCount: 2,
  },
  {
    name: 'SBC (sr,S),Y',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xf3,
    bytesCount: 2,
  },
  {
    name: 'SBC dp,X',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xf5,
    bytesCount: 2,
  },
  {
    name: 'SBC [dp],Y',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xf7,
    bytesCount: 2,
  },
  {
    name: 'SBC addr,Y',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xf9,
    bytesCount: 3,
  },
  {
    name: 'SBC addr,X',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xfd,
    bytesCount: 3,
  },
  {
    name: 'SBC long,X',
    description: 'Subtract with Borrow from Accumulator',
    hex: 0xff,
    bytesCount: 4,
  },
  { name: 'SEC', description: 'Set Carry Flag', hex: 0x38, bytesCount: 1 },
  { name: 'SED', description: 'Set Decimal Flag', hex: 0xf8, bytesCount: 1 },
  {
    name: 'SEI',
    description: 'Set Interrupt Disable Flag',
    hex: 0x78,
    bytesCount: 1,
  },
  {
    name: 'SEP #const',
    description: 'Set Processor Status Bits',
    hex: 0xe2,
    bytesCount: 2,
  },
  {
    name: 'STA (dp,X)',
    description: 'Store Accumulator to Memory',
    hex: 0x81,
    bytesCount: 2,
  },
  {
    name: 'STA sr,S',
    description: 'Store Accumulator to Memory',
    hex: 0x83,
    bytesCount: 2,
  },
  {
    name: 'STA dp',
    description: 'Store Accumulator to Memory',
    hex: 0x85,
    bytesCount: 2,
  },
  {
    name: 'STA [dp]',
    description: 'Store Accumulator to Memory',
    hex: 0x87,
    bytesCount: 2,
  },
  {
    name: 'STA addr',
    description: 'Store Accumulator to Memory',
    hex: 0x8d,
    bytesCount: 3,
  },
  {
    name: 'STA long',
    description: 'Store Accumulator to Memory',
    hex: 0x8f,
    bytesCount: 4,
  },
  {
    name: 'STA (dp),Y',
    description: 'Store Accumulator to Memory',
    hex: 0x91,
    bytesCount: 2,
  },
  {
    name: 'STA (dp)',
    description: 'Store Accumulator to Memory',
    hex: 0x92,
    bytesCount: 2,
  },
  {
    name: 'STA (sr,S),Y',
    description: 'Store Accumulator to Memory',
    hex: 0x93,
    bytesCount: 2,
  },
  {
    name: 'STA _dp_X',
    description: 'Store Accumulator to Memory',
    hex: 0x95,
    bytesCount: 2,
  },
  {
    name: 'STA [dp],Y',
    description: 'Store Accumulator to Memory',
    hex: 0x97,
    bytesCount: 2,
  },
  {
    name: 'STA addr,Y',
    description: 'Store Accumulator to Memory',
    hex: 0x99,
    bytesCount: 3,
  },
  {
    name: 'STA addr,X',
    description: 'Store Accumulator to Memory',
    hex: 0x9d,
    bytesCount: 3,
  },
  {
    name: 'STA long,X',
    description: 'Store Accumulator to Memory',
    hex: 0x9f,
    bytesCount: 4,
  },
  { name: 'STP', description: 'Stop Processor', hex: 0xdb, bytesCount: 1 },
  {
    name: 'STX dp',
    description: 'Store Index Register X to Memory',
    hex: 0x86,
    bytesCount: 2,
  },
  {
    name: 'STX addr',
    description: 'Store Index Register X to Memory',
    hex: 0x8e,
    bytesCount: 3,
  },
  {
    name: 'STX dp,Y',
    description: 'Store Index Register X to Memory',
    hex: 0x96,
    bytesCount: 2,
  },
  {
    name: 'STY dp',
    description: 'Store Index Register Y to Memory',
    hex: 0x84,
    bytesCount: 2,
  },
  {
    name: 'STY addr',
    description: 'Store Index Register Y to Memory',
    hex: 0x8c,
    bytesCount: 3,
  },
  {
    name: 'STY dp,X',
    description: 'Store Index Register Y to Memory',
    hex: 0x94,
    bytesCount: 2,
  },
  {
    name: 'STZ dp',
    description: 'Store Zero to Memory',
    hex: 0x64,
    bytesCount: 2,
  },
  {
    name: 'STZ dp,X',
    description: 'Store Zero to Memory',
    hex: 0x74,
    bytesCount: 2,
  },
  {
    name: 'STZ addr',
    description: 'Store Zero to Memory',
    hex: 0x9c,
    bytesCount: 3,
  },
  {
    name: 'STZ addr,X',
    description: 'Store Zero to Memory',
    hex: 0x9e,
    bytesCount: 3,
  },
  {
    name: 'TAX',
    description: 'Transfer Accumulator to Index Register X',
    hex: 0xaa,
    bytesCount: 1,
  },
  {
    name: 'TAY',
    description: 'Transfer Accumulator to Index Register Y',
    hex: 0xa8,
    bytesCount: 1,
  },
  {
    name: 'TCD',
    description: 'Transfer 16-bit Accumulator to Direct Page Register',
    hex: 0x5b,
    bytesCount: 1,
  },
  {
    name: 'TCS',
    description: 'Transfer 16-bit Accumulator to Stack Pointer',
    hex: 0x1b,
    bytesCount: 1,
  },
  {
    name: 'TDC',
    description: 'Transfer Direct Page Register to 16-bit Accumulator',
    hex: 0x7b,
    bytesCount: 1,
  },
  {
    name: 'TRB dp',
    description: 'Test and Reset Memory Bits Against Accumulator',
    hex: 0x14,
    bytesCount: 2,
  },
  {
    name: 'TRB addr',
    description: 'Test and Reset Memory Bits Against Accumulator',
    hex: 0x1c,
    bytesCount: 3,
  },
  {
    name: 'TSB dp',
    description: 'Test and Set Memory Bits Against Accumulator',
    hex: 0x4,
    bytesCount: 2,
  },
  {
    name: 'TSB addr',
    description: 'Test and Set Memory Bits Against Accumulator',
    hex: 0x0c,
    bytesCount: 3,
  },
  {
    name: 'TSC',
    description: 'Transfer Stack Pointer to 16-bit Accumulator',
    hex: 0x3b,
    bytesCount: 1,
  },
  {
    name: 'TSX',
    description: 'Transfer Stack Pointer to Index Register X',
    hex: 0xba,
    bytesCount: 1,
  },
  {
    name: 'TXA',
    description: 'Transfer Index Register X to Accumulator',
    hex: 0x8a,
    bytesCount: 1,
  },
  {
    name: 'TXS',
    description: 'Transfer Index Register X to Stack Pointer',
    hex: 0x9a,
    bytesCount: 1,
  },
  {
    name: 'TXY',
    description: 'Transfer Index Register X to Index Register Y',
    hex: 0x9b,
    bytesCount: 1,
  },
  {
    name: 'TYA',
    description: 'Transfer Index Register Y to Accumulator',
    hex: 0x98,
    bytesCount: 1,
  },
  {
    name: 'TYX',
    description: 'Transfer Index Register Y to Index Register X',
    hex: 0xbb,
    bytesCount: 1,
  },
  { name: 'WAI', description: 'Wait for Interrupt', hex: 0xcb, bytesCount: 1 },
  {
    name: 'WDM',
    description: 'Reserved for Future Expansion',
    hex: 0x42,
    bytesCount: 2,
  },
  {
    name: 'XBA',
    description: 'Exchange B and A 8-bit Accumulators',
    hex: 0xeb,
    bytesCount: 1,
  },
  {
    name: 'XCE',
    description: 'Exchange Carry and Emulation Flags',
    hex: 0xfb,
    bytesCount: 1,
  },
];

export const OPCODES_MAP: Record<number, Opcode> = OPCODES.reduce(
  (acc, i) => {
    acc[i.hex] = i;
    return acc;
  },
  {} as Record<number, Opcode>,
);
